INSERT INTO courses (name, category, teacher) VALUES ('Mathematics', 'Exact Sciences', 'Juan Diego Ossa');
INSERT INTO courses (name, category, teacher) VALUES ('Biology', 'Sciences', 'Leandro Jaramillo');
INSERT INTO courses (name, category, teacher) VALUES ('Programming', 'Technology', 'Neiro Figueroa');
INSERT INTO courses (name, category, teacher) VALUES ('Chemistry', 'Exact Sciences', 'Maria Gomez');
INSERT INTO courses (name, category, teacher) VALUES ('History', 'Social Sciences', 'Carlos Ruiz');
INSERT INTO courses (name, category, teacher) VALUES ('Physics', 'Exact Sciences', 'Ana Torres');
INSERT INTO courses (name, category, teacher) VALUES ('Literature', 'Humanities', 'Luis Martinez');
INSERT INTO courses (name, category, teacher) VALUES ('Art', 'Humanities', 'Clara Lopez');
INSERT INTO courses (name, category, teacher) VALUES ('Economics', 'Social Sciences', 'Fernando Diaz');
INSERT INTO courses (name, category, teacher) VALUES ('Psychology', 'Social Sciences', 'Elena Castro');
INSERT INTO courses (name, category, teacher) VALUES ('Graphic Design', 'Technology', 'Pedro Sanchez');
INSERT INTO courses (name, category, teacher) VALUES ('Music', 'Arts', 'Sofia Hernandez');

INSERT INTO students (name, last_name, age, course_id) VALUES ('Laura', 'Garcia', '23', 1);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Diego', 'Martinez', '27', 2);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Camila', 'Rojas', '20', 3);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Felipe', 'Morales', '25', 4);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Valentina', 'Cruz', '22', 5);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Mateo', 'Salazar', '24', 6);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Isabella', 'Perez', '21', 7);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Andres', 'Jimenez', '26', 8);
INSERT INTO students (name, last_name, age, course_id) VALUES ('Nicolas', 'Alvarez', '23', 9);
